spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/photobooth
    username: photobooth
    password: photobooth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.iitsaii.photobooth: debug
