spring:
  application:
    name: photobooth
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

toss:
  secret-key: ${TOSS_SECRET_KEY}
